### ISSUE TITLE
 Signature verification failed

### ISSUE THREAD

**Issue by BrannonR** [DeepSkyForge/GraXpertSuite4PixInsight#1]
I updated Pix and tried to update GraXpert today, but when I try to update the repo Im getting this error.  

https://pixinsight.deepskyforge.com/update/graxpert/: Parsing repository update information: Parsing Signature element (line=1 offset=0): Unknown code signing identity 'JoelVallier'

**Comment by omeganon** [comment]
+1. Same error.

**Comment by horrifiedonlooker** [comment]
I had the exact same problem and tried everything that was suggested so I finally downloaded and installed build 1597 and everything works now!!

**Comment by omeganon** [comment]
Agreed. Looks like a specific minimum build is required.

**Comment by DeepSkyForge** [comment]
@horrifiedonlooker is correct; you need a minimum of PixInsight 1.8.9-2, build 1597, which was released on January 19th, 2024.
Indeed, my Certified PixInsight Developer ID (JoelVallier) was introduced in this version.
That why all previous versions will reject the signature.

If you absolutely must install the script on a previous version, the only option is to download the ZIP file, remove all *.xsgn files, and proceed with a manual installation. However, be aware that you will likely need to adjust security parameters to allow the execution of unsigned scripts. That why I do not recommend this option, but it is the only possibility.

I will include a note on http://www.deepskyforge.com/

**Comment by DeepSkyForge** [comment]
Web page https://www.deepskyforge.com/ updated (defined clearly minimal version required).
