### ISSUE TITLE
Exit error code 255 in PixInsight

### ISSUE THREAD

**Issue by daveswin** [DeepSkyForge/GraXpertSuite4PixInsight#3]
After updating PI to latest build (1605 of 2024-03-23) and GraXpert to 3.0.0 and downloading the latest from the repository I get this error:
GraXpert: Processing view: masterLight_BIN_1_6252x4176_EXPOSURE_300_00s_FILTER_O3_mono_drizzle_2x
Writing image: w=12364 h=8170 n=1 Gray Float32
Mode background extraction
graxpert /tmp/PixInsight.xisf -cli -ai 1.0.1 -smoothing 0.000 -correction Subtraction
Status: Exit error code 255
341.933 ms

Running GraXpert stand-alone works fine. It's just the PI invocation having issues.

My system if Kubuntu 22.04 Kernel v. 15.0-102-generic (64-bit) on a AMD Ryzen 9 5900X with 64 GiB Ram

**Comment by daveswin** [comment]
I dug into this a bit more and it seems the AI model file wasn't present. (though I'm not sure why) When re-downloaded the script runs. (but I get cuda related issues that don't seem to impact the final result... had them before too.)

**Comment by DeepSkyForge** [comment]
Sorry, I didn't saw your message.
Indeed, I released GraXpert Process and decided to stop the script.
Does suggestion from daveswin fixed the issue?
Do you have same problem with last version of GraXpert Process?
You can get process from my website https://www.deepskyforge.com/index.html
If so, please report issue here: https://github.com/DeepSkyForge/GraXpert4PixInsight/issues
Thanks @daveswin for your suggestion.
